apiVersion: v1
kind: Service
metadata:
  name: jenkins-lb-ui
  labels:
    app: notepad
spec:
  selector:
    app: jenkins
    role: master
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31001
    name: ui-lb
  type: LoadBalancer
