apiVersion: v1
kind: Service
metadata:
  name: artifactory-lb-service
  labels:
    app: artifactory
spec:
  selector:
    app: artifactory
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081
    nodePort: 31011
    name: ui-lb
  type: LoadBalancer
